
# Lenovo BMC Reset Configuration Role - Main Tasks

- name: Configure BMC
  hosts: bmc_servers
  tasks:
    - delegate_to: "{{ bmc_jump_host }}"
      block:
       - name: Include network tasks
         include_tasks: configure_network.yml

       - name: Include account tasks
         include_tasks: configure_account.yml

       - name: Include user tasks
         include_tasks: configure_users.yml

#- name: Include bmc reset tasks
#  include_tasks: temp.yml

#- name: Include network tasks
#  include_tasks: configure_network.yml

#- name: Include account tasks
#  include_tasks: configure_account.yml

#- name: Include user tasks
#  include_tasks: configure_users.yml

