
# Lenovo BMC Reset Configuration Role - Main Tasks

- name: Include network tasks
  include_tasks: configure_network.yml

- name: Include account tasks
  include_tasks: configure_account.yml

- name: Include user tasks
  include_tasks: configure_users.yml

