
# roles/configure_raid/tasks/main.yml

- name: Discover configuration
  include_tasks: discover.yml

#- name: ufi boot
 # include_tasks: temp.yml
  
- name: Check Power State
  include_tasks: manage_power.yml

- name: Validate Storage Controller
  include_tasks: validate_controller.yml

- name: Validate disks
  include_tasks: validate_disks.yml

- name: Validate volume
  include_tasks: validate_volumes.yml
  
#- name: Delete volume
 # include_tasks: delete_volumes.yml

#- name: Create volume
 # include_tasks: create_volume.yml
