# roles/bmc_config/tasks/main.yml

- name: Discover vendor
  include_tasks: discover.yml

#- name: Clean Jobs
 # include_tasks: clean_jobs.yml

#- name: Configure System Lockdown
 # include_tasks: check_lockdown.yml

#- name: Configure Network
 # include_tasks: configure_network.yml

#- name: Configure Ports
 # include_tasks: configure_ports.yml

#- name: Configure Logging
 # include_tasks: configure_logging.yml

#- name: Configure Power Policy
 # include_tasks: configure_power_policy.yml

#- name: Configure IPMI
 # include_tasks: configure_ipmi.yml

- name: Configure Operating Mode
  include_tasks: configure_operating_mode.yml

#- name: Run vendor Redfish extensions
 # include_tasks: "vendors/{{ detected_vendor }}/redfish.yml"

#- name: Run SSH fallback if required
 # include_tasks: "vendors/{{ detected_vendor }}/ssh.yml"
  #when: bmc_capabilities.requires_ssh_for_bios


#- name: Configure BMC Network
 # include_tasks: network.yml

#- name: Configure NTP
#  include_tasks: ntp.yml

#- name: Configure DNS
#  include_tasks: dns.yml

#- name: Configure User Accounts
 # include_tasks: users.yml

