# roles/bmc_config/tasks/network.yml

- name: Get Ethernet Interfaces
  uri:
    url: "https://{{ bmc_ip }}{{ redfish_manager_url }}/EthernetInterfaces"
    method: GET
    user: "{{ bmc_user }}"
    password: "{{ bmc_password }}"
    validate_certs: false
  register: eth_list
