- name: Get current power state
  uri:
    url: "https://{{ ansible_host }}/redfish/v1/Systems/1"
    method: GET
    user: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    force_basic_auth: yes
    validate_certs: no
  register: dell_power
